ShortRent.Web/Models/Person/PassWordEditModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ShortRent.Web.Models
{
    public class PassWordEditModel
    {
        public int ID { get; set; }
        public string OldPassWord{get;set;}
        public string PassWord { get; set; }
        public string ConfirmPassWord { get; set; }
    }
}

ShortRent.Web/Models/Person/PersonAdminEditModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ShortRent.Web.Models
{
    public class PersonAdminEditModel
    {
        public int ID { get; set; }
        /// <summary>
        /// 姓名
        /// </summary>
        public string Name { get; set; }
      
        /// <summary>
        /// 用户类别 0代表前台用户，1 代表后台用户
        /// </summary>
        public bool Type { get; set; }
        /// <summary>
        /// 个人头像
        /// </summary>
        public string PerImage { get; set; }
        /// <summary>
        /// 密码
        /// </summary>
        public string PassWord { get; set; }
        /// <summary>
        /// 职位
        /// </summary>
        public string Position { get; set; }
        public string PersonDetail { get; set; }
        /// <summary>
        /// QQ
        /// </summary>
        public string Qq { get; set; }
        /// <summary>
        /// 微信
        /// </summary>
        public string WeChat { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime CreateTime { get; set; }
        /// <summary>
        /// 是否删除 false 不删除 true 删除
        /// </summary>
    }
}

ShortRent.Web/Models/Person/PersonAdminHumanEditModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ShortRent.Web.Models
{
    public class PersonAdminHumanEditModel
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string PerImage { get; set; }
        public string PassWord { get; set; }

        public string Position { get; set; }
        public string PersonDetail { get; set; }
        public string Qq { get; set; }
        public string WeChat { get; set; }
        public DateTime CreateTime { get; set; }

    }
}

ShortRent.Web/Models/Person/PersonAdminIndexModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ShortRent.Web.Models
{
    public class PersonAdminIndexModel
    {
        public int Id { get; set; }
        /// <summary>
        /// 姓名
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 个人头像
        /// </summary>
        public string PerImage { get; set; }
        /// <summary>
        /// 职位
        /// </summary>
        public string Position { get; set; }

        public string PersonDetail { get; set; }
        /// <summary>
        /// QQ
        /// </summary>
        public string Qq { get; set; }
        /// <summary>
        /// 微信
        /// </summary>
        public string WeChat { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime CreateTime { get; set; }
    }
}

ShortRent.Web/Models/Person/PersonAdminUpdate.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ShortRent.Web.Models
{
    public class PersonAdminUpdate
    {
        public int ID { get; set; }
        /// <summary>
        /// 姓名
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 出生日期
        /// </summary>
        public DateTime Birthday { get; set; }
        /// <summary>
        /// null保密 true 男 false 女
        /// </summary>
        public bool? Sex { get; set; }
        /// <summary>
        /// 用户类别 0代表前台用户，1 代表后台用户
        /// </summary>
        public bool Type { get; set; }
        /// <summary>
        /// 个人头像
        /// </summary>
        public string PerImage { get; set; }
        /// <summary>
        /// 密码
        /// </summary>
        public string PassWord { get; set; }
        /// <summary>
        /// 信用积分
        /// </summary>
        public decimal CreditScore { get; set; }
        /// <summary>
        /// 身份证号
        /// </summary>
        public string IdCard { get; set; }
        /// <summary>
        /// 职位
        /// </summary>
        public string Position { get; set; }
        public string PersonDetail { get; set; }
        /// <summary>
        /// 用户排序
        /// </summary>
        public int PerOrder { get; set; }
        /// <summary>
        /// QQ
        /// </summary>
        public string Qq { get; set; }
        /// <summary>
        /// 微信
        /// </summary>
        public string WeChat { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime CreateTime { get; set; }
        /// <summary>
        /// 是否删除 false 不删除 true 删除
        /// </summary>
        public bool IsDelete { get; set; }
    }
}

ShortRent.Web/Models/Person/PersonLoginModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ShortRent.Web.Models
{
    public class PersonLoginModel
    {
        /// <summary>
        /// 用户名
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 密码
        /// </summary>
        public string PassWord { get; set; }
        /// <summary>
        /// 记住我
        /// </summary>
        public bool ReadMe { get; set; }
    }
}

ShortRent.Web/Models/Person/PersonViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ShortRent.Web.Models
{
    public class PersonViewModel
    {
        /// <summary>
        /// 编号
        /// </summary>
        public int ID { get; set; }
        /// <summary>
        /// 姓名
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 出生日期
        /// </summary>
        public DateTime Birthday { get; set; }
        /// <summary>
        /// 性别 false女 true 男  null保密
        /// </summary>
        public bool? Sex { get; set; }
    }
}

ShortRent.Web/Models/PersonViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ShortRent.Web.Models
{
    public class PersonViewModel
    {
        /// <summary>
        /// 姓名
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 出生日期
        /// </summary>
        public DateTime Birthday { get; set; }
    }
}

ShortRent.Web/Controllers/PersonController.cs
using AutoMapper;
using ShortRent.Core;
using ShortRent.Core.Domain;
using ShortRent.Core.Language;
using ShortRent.Core.Log;
using ShortRent.Service;
using ShortRent.Web.Models;
using ShortRent.WebCore.MVC;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ShortRent.Web.Controllers
{
    public class PersonController : BaseController
    {
        #region Field 
        private readonly IPersonService _personService;
        private readonly IRoleService _roleService;
        private readonly IHistoryOperatorService _historyOperatorService;
        private readonly IAutnenticationProvider _authenticationProvider;
        //autoMapper
        private readonly IMapper _mapper;
        private readonly MapperConfiguration _mapperConfig;
        private readonly ILogger _logger;
        #endregion

        #region Construction
        public PersonController(IPersonService personService,
            IRoleService roleService
            ,IMapper mapper,
            MapperConfiguration mapperConfiguration,ILogger logger
            ,IHistoryOperatorService historyOperator
            ,IAutnenticationProvider autnentication)
        {
            this._personService = personService;
            this._roleService = roleService;
            this._historyOperatorService = historyOperator;
            this._authenticationProvider = autnentication;
            this._mapper = mapper;
            this._mapperConfig = mapperConfiguration;
            this._logger = logger;
        }
        #endregion

        #region Method
        public ActionResult List()
        {
            ViewBag.Title = "后台用户管理";
            ViewBag.Content = "列表";
            return View();
        }
        public ActionResult Index(int? pageSize,int? pageNumber,string AdminName)
        {
            List<PersonAdminIndexModel> list = null;
            PagedListViewModel<PersonAdminIndexModel> paged = new PagedListViewModel<PersonAdminIndexModel>();
            try
            {
                int total;
                var persons = _personService.GetTypePerson(pageSize ?? 0, pageNumber ?? 0,AdminName, 1, out total);
                if(persons.Any())
                {
                    list = _mapper.Map<List<PersonAdminIndexModel>>(persons);
                }
                else
                {
                    list = new List<PersonAdminIndexModel>();
                }
                paged.Rows = list;
                paged.Total = total;
            }
            catch(Exception e)
            {
                list = new List<PersonAdminIndexModel>();
                _logger.Debug("获得列表时出现错误",e);
                throw e;
            }
            return Json(paged,JsonRequestBehavior.AllowGet);
        }
       
        public ActionResult Create()
        {
            ViewBag.Title = "后台用户管理";
            ViewBag.Content = "后台用户创建";
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PersonAdminEditModel personAdminEditModel, HttpPostedFileBase headPhoto)
        {
            try
            {
                    Person person = new Person();
                    Dictionary<string, string> str = new Dictionary<string, string>();//上传成功后返回文件的信息
                    if (headPhoto != null)
                    {
                        //上传文件到服务器
                        str = UploadImg(headPhoto, "/Content/Images/AdminImg");
                        if (str["Result"].ToString() == "0")
                        {
                            return Json(new AjaxJson() { HttpCodeResult = (int)HttpStatusCode.InternalServerError, Message = "上传文件格式不正确，请重新上传，所修改数据未被保留！" });
                        }
                    }
                    //如果数据库中存在和姓名一样的要填写表单。
                    Person ifPerson = _personService.GetPersons().Where(t => t.Type == true).SingleOrDefault(t => t.Name == personAdminEditModel.Name);
                    if (ifPerson != null)
                    {
                        return Json(new AjaxJson() { HttpCodeResult = (int)HttpStatusCode.InternalServerError, Message = $"已经存在名称为{personAdminEditModel.Name}的人，请重新调整。" });
                    }
                    person = _mapper.Map<Person>(personAdminEditModel);
                    person.CreateTime = DateTime.Now;
                    if(str.Keys.Any(c => c == "ImagePath"))
                    {
                        person.PerImage = str["ImagePath"];
                    }
                    person.IdCard = "000000";
                    person.Type = true;
                    person.Birthday = DateTime.Now.AddYears(-18);
                    person.CreditScore = 0;
                    _personService.CreatePerson(person);                   
                    PersonAdminHumanEditModel human = _mapper.Map<PersonAdminHumanEditModel>(person);
                    //将修改的信息加入记录中去
                    HistoryOperator history = new HistoryOperator()
                    {
                        CreateTime = DateTime.Now,
                        DetailDescirption = GetDescription<PersonAdminHumanEditModel>("创建了一个后台用户，详情", human),
                        EntityModule = "用户管理",
                        Operates = "后台用户创建",
                        PersonId = GetCurrentPerson().ID
                    };
                    _historyOperatorService.CreateHistoryOperator(history);
            }
            catch(Exception e)
            {
                _logger.Debug("创建用户失败",e);
                throw e;
            }
            return Json(new AjaxJson() { HttpCodeResult = (int)HttpStatusCode.OK, Message = "创建后台用户成功！", Url = Url.Action(nameof(PersonController.List)) });
        }

        public ActionResult Edit(int id)
        {
            ViewBag.Title = "用户管理";
            ViewBag.Content = "后台用户编辑";
            PersonAdminEditModel person = new PersonAdminEditModel();
            try
            {
                person = _mapper.Map<PersonAdminEditModel>(_personService.GetPerson(id));
            }
            catch(Exception e)
            {
                _logger.Debug("显示编辑出错！",e);
                throw e;
            }
            return View("Create",person);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PersonAdminEditModel model, HttpPostedFileBase headPhoto)
        {
            try
            {
                    //判断上传的图片是否为空
                    Person person = new Person();
                    Dictionary<string, string> str = new Dictionary<string, string>();//上传成功后返回文件的信息
                    if (headPhoto != null)
                    {
                        //上传文件到服务器
                        str = UploadImg(headPhoto, "/Content/Images/AdminImg");
                        if (str["Result"].ToString() == "0")
                        {
                            //上传文件失败出错！
                            return Json(new AjaxJson() { HttpCodeResult = (int)HttpStatusCode.InternalServerError, Message = "上传文件格式不正确，请重新上传，所修改数据未被保留！", Url = Url.Action(nameof(PersonController.PersonAdminDetail)) });
                        }
                    }
                    //将该模型映射成
                    person = _mapper.Map<Person>(model);
                    if (str.Keys.Any(c=>c=="ImagePath"))
                    {
                        person.PerImage = str["ImagePath"];
                    }
                    //先获取之前的后台 用户信息
                    Person oldPerson = _personService.GetPerson(person.ID);
                    //如果修改的模型的姓名和数据库中的模型相同，那么重新修改
                    if(oldPerson.Name!=person.Name)
                    {
                        Person ifPerson = _personService.GetPersons().Where(t => t.Type == true).FirstOrDefault(p=>p.Name==person.Name);
                        if(ifPerson!=null)
                        {
                            return Json(new AjaxJson() { HttpCodeResult = (int)HttpStatusCode.InternalServerError, Message = $"已经存在名称为{person.Name}的人，请重新调整。" });
                        }
                    }
                    var oldHumanPerson = _mapper.Map<PersonAdminHumanEditModel>(oldPerson);
                    var newHumanPerson = _mapper.Map<PersonAdminHumanEditModel>(person);
                    //将更改提交到数据库
                    _personService.UpdatePerson(person);
                    //将这样的修改记录存入数据库中去
                    HistoryOperator history = new HistoryOperator()
                    {
                        CreateTime = DateTime.Now,
                        DetailDescirption = GetDescription<PersonAdminHumanEditModel>("修改了一个后台用户，详情",newHumanPerson,oldHumanPerson),
                        EntityModule = "用户管理",
                        Operates = "后台用户编辑",
                        PersonId = GetCurrentPerson().ID
                    };
                    _historyOperatorService.CreateHistoryOperator(history);
            }
            catch(Exception e)
            {
                _logger.Debug("后台用户信息编辑出现错误",e);
                throw e;
            }
            return Json(new AjaxJson() { HttpCodeResult = (int)HttpStatusCode.OK, Message = "修改用户成功！", Url = Url.Action(nameof(PersonController.List)) });
        }
        public ActionResult ReSetPassWord(int id)
        {
            try
            {
                //首先得到要重置密码的用户
                Person person = _personService.GetPerson(id);
                PersonAdminUpdate adminPerson = null;
                //重置密码为123456
                if (person.PassWord != "123456")
                {
                    person.PassWord = "123456";
                }
                //将用户放到adminPerson作为缓冲
                adminPerson = _mapper.Map<PersonAdminUpdate>(person);
                Person model = _mapper.Map<Person>(adminPerson);
                _personService.UpdatePerson(model);
                //将更改密码写入历史操作中去

ShortRent.Web/Views/Person/AssignRoles.cshtml
@model SelectList
@{
    Layout = "~/Views/Shared/AdminMaster.cshtml";
}

@section Styles{
    @Styles.Render("~/Styles/IcheckSkins")
}
@using (Ajax.BeginForm(new AjaxOptions() { HttpMethod = "post", OnSuccess = "SuccessAssign" }))
{
    @Html.AntiForgeryToken()
    @Html.Hidden("personId", (int)ViewBag.ID)
    <div class="form-horizontal box">
        <div class="box-body">
            <div class="form-group col-md-12 ">
                @foreach (var group in Model.Items.OfType<SelectListItem>())
                {
                    <div class="col-md-2">
                        <input type="checkbox" name="roleIds" value="@group.Value" @(group.Selected ? Html.Raw("checked") : null) />
                        <span class="mar-rightPri">@group.Text</span>
                    </div>
                }
                </div>
            <div class="form-group col-md-12">
                <div class="row text-center marTop-xs">
                    <input type="submit" value="提交" class="btn btn-success" />
                </div>
            </div>
        </div>`
    </div>
}



@section Scripts{
    @Scripts.Render("~/Scripts/Icheck")
    @Scripts.Render("~/Scripts/Jquery-Ajax-unobtrusive")
    @Scripts.Render("~/Scripts/AssignRolesIndex")
}

ShortRent.Web/Views/Person/Create.cshtml
@model PersonAdminEditModel
@{
    Layout = "~/Views/Shared/AdminMaster.cshtml";
}
@section Styles{
    @Styles.Render("~/Content/jQuery-File-Upload")
}
@if (Model == null)
{
    using (Html.BeginForm("Create", "Person", FormMethod.Post, new { enctype = "multipart/form-data", ID = "frmSave", Name = "frmSave" }))
    {
        <div class="form-horizontal box">
            <div class="box-body">
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-error" })
                <div class="form-group col-md-6">
                    <div class="row">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-4 text-right" })
                        <div class="col-xs-12 col-md-8">
                            <div class="row clear-margin">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control col-md-8" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-error" })
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group col-md-6">
                    <div class="row">
                        @Html.LabelFor(model => model.PassWord, htmlAttributes: new { @class = "control-label col-md-4 text-right" })
                        <div class="col-xs-12 col-md-8">
                            <div class="row clear-margin">
                                @Html.PasswordFor(model => model.PassWord, htmlAttributes: new { @class = "form-control col-md-8" })
                                @Html.ValidationMessageFor(model => model.PassWord, "", new { @class = "text-error" })
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group col-md-6">
                    <div class="row">
                        @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-md-4 text-right" })
                        <div class="col-xs-12 col-md-8">
                            <div class="row clear-margin">
                                @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control col-md-8" } })
                                @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-error" })
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group col-md-6">
                    <div class="row">
                        @Html.LabelFor(model => model.Qq, htmlAttributes: new { @class = "control-label col-md-4 text-right" })
                        <div class="col-xs-12 col-md-8">
                            <div class="row clear-margin">
                                @Html.EditorFor(model => model.Qq, new { htmlAttributes = new { @class = "form-control col-md-8" } })
                                @Html.ValidationMessageFor(model => model.Qq, "", new { @class = "text-error" })
                            </div>
                        </div>

                    </div>
                </div>

                <div class="form-group col-md-6">
                    <div class="row">
                        @Html.LabelFor(model => model.WeChat, htmlAttributes: new { @class = "control-label col-md-4 text-right" })
                        <div class="col-xs-12 col-md-8">
                            <div class="row clear-margin">
                                @Html.EditorFor(model => model.WeChat, new { htmlAttributes = new { @class = "form-control col-md-8" } })
                                @Html.ValidationMessageFor(model => model.WeChat, "", new { @class = "text-error" })
                            </div>
                        </div>

                    </div>
                </div>

                <div class="form-group col-md-12">
                    <div class="row">
                        @Html.LabelFor(model => model.PersonDetail, htmlAttributes: new { @class = "control-label col-md-2 text-right" })
                        <div class="col-xs-12 col-md-10">
                            <div class="row clear-margin">
                                @Html.TextAreaFor(model => model.PersonDetail, htmlAttributes: new { @class = "form-control col-md-12", rows = "5" })
                                @Html.ValidationMessageFor(model => model.PersonDetail, "", new { @class = "text-error" })
                            </div>
                        </div>

                    </div>
                </div>

                <div class="form-group col-md-12">
                    <div class="row">
                        @Html.LabelFor(model => model.PerImage, htmlAttributes: new { @class = "col-xs-2 control-label col-md-2 text-right" })
                        <div class="col-xs-4 col-sm-1">
                            <div class="row clear-margin ">
                                <img id="headPhoto" class="images-response" src="" />
                            </div>
                        </div>
                        <div class="col-sm-9">
                            <span class="btn btn-success fileinput-button">
                                <i class="glyphicon glyphicon-plus"></i>
                                <span>选择图片</span>
                                <input type="hidden" name="PerImage" value="admin.png" />
                                <input type="file" name="headPhoto" onchange="ShowImage()">
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-12">
                    <div class="row text-center marTop-xs">
                        <input type="button" value="提交" class="btn btn-success" />
                    </div>
                </div>
            </div>
        </div>
    }
}
else
{
    using (Html.BeginForm("Edit", "Person", FormMethod.Post, new { enctype = "multipart/form-data", ID = "frmSave", Name = "frmSave" }))
    {
        <div class="form-horizontal box">
            <div class="box-body">
                @Html.AntiForgeryToken()
                @Html.HiddenFor(c => c.ID)
                @Html.HiddenFor(model => model.PassWord)
                @Html.HiddenFor(model => model.CreateTime)
                @Html.HiddenFor(model => model.Type)
                @Html.HiddenFor(model=>model.IdCard)
                @Html.HiddenFor(model=>model.Birthday)
                @Html.ValidationSummary(true, "", new { @class = "text-error" })
                <div class="form-group col-md-6">
                    <div class="row">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-4 text-right" })
                        <div class="col-xs-12 col-md-8">
                            <div class="row clear-margin">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control col-md-8" } })
                                <input type="hidden" id="hidName" value="@Model.Name" />
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-error" })
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group col-md-6">
                    <div class="row">
                        @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-md-4 text-right" })
                        <div class="col-xs-12 col-md-8">
                            <div class="row clear-margin">
                                @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control col-md-8" } })
                                <input type="hidden" id="hidPosition" value="@Model.Position" />
                                @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-error" })
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group col-md-6">
                    <div class="row">
                        @Html.LabelFor(model => model.Qq, htmlAttributes: new { @class = "control-label col-md-4 text-right" })
                        <div class="col-xs-12 col-md-8">
                            <div class="row clear-margin">
                                @Html.EditorFor(model => model.Qq, new { htmlAttributes = new { @class = "form-control col-md-8" } })
                                <input type="hidden" id="hidQq" value="@Model.Qq" />
                                @Html.ValidationMessageFor(model => model.Qq, "", new { @class = "text-error" })
                            </div>
                        </div>

                    </div>
                </div>

                <div class="form-group col-md-6">
                    <div class="row">
                        @Html.LabelFor(model => model.WeChat, htmlAttributes: new { @class = "control-label col-md-4 text-right" })
                        <div class="col-xs-12 col-md-8">
                            <div class="row clear-margin">
                                @Html.EditorFor(model => model.WeChat, new { htmlAttributes = new { @class = "form-control col-md-8" } })
                                <input type="hidden" id="hidWeChat" value="@Model.WeChat" />
                                @Html.ValidationMessageFor(model => model.WeChat, "", new { @class = "text-error" })
                            </div>
                        </div>

                    </div>
                </div>

                <div class="form-group col-md-12">
                    <div class="row">
                        @Html.LabelFor(model => model.PersonDetail, htmlAttributes: new { @class = "control-label col-md-2 text-right" })
                        <div class="col-xs-12 col-md-10">
                            <div class="row clear-margin">
                                @Html.TextAreaFor(model => model.PersonDetail, htmlAttributes: new { @class = "form-control col-md-12", rows = "5" })
                                <input type="hidden" id="hidPersonDetail" value="@Model.PersonDetail" />
                                @Html.ValidationMessageFor(model => model.PersonDetail, "", new { @class = "text-error" })
                            </div>
                        </div>

                    </div>
                </div>

                <div class="form-group col-md-12">
                    <div class="row">
                        @Html.LabelFor(model => model.PerImage, htmlAttributes: new { @class = "col-xs-2 control-label col-md-2 text-right" })
                        <div class="col-xs-4 col-sm-1">
                            <div class="row clear-margin ">
                                <img id="headPhoto" class="images-response" src="~/Content/Images/AdminImg/@Model.PerImage" />
                            </div>
                        </div>
                        <div class="col-sm-9">
                            <span class="btn btn-success fileinput-button">
                                <i class="glyphicon glyphicon-plus"></i>
                                <span>选择图片</span>
                                <input type="hidden" name="PerImage" value="@Model.PerImage" />
                                <input type="hidden" id="PerImage" value="~/Content/Images/AdminImg/@Model.PerImage" />
                                <input type="file" name="headPhoto" onchange="ShowImage()">
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-12">
                    <div class="row text-center marTop-xs">
                        <input type="button" value="提交" class="btn btn-success" />
                    </div>
                </div>
            </div>
        </div>
    }
}

@section Scripts
{
    @Scripts.Render("~/Scripts/Jquery-Form")
    @Scripts.Render("~/Scripts/PersonCreateOrEdit")
}

ShortRent.Web/Views/Person/Home.cshtml
@{
    Layout = "~/Views/Shared/AdminMaster.cshtml";
}

<h2>欢迎登陆到网站后台</h2>

ShortRent.Web/Views/Person/Index.cshtml
@model IEnumerable<PersonViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminMaster.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Birthday)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sex)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Birthday)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sex)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

ShortRent.Web/Views/Person/Test.cshtml
@{
    Layout = "~/Views/Shared/AdminMaster.cshtml";
}

<h2>@ViewBag.Data</h2>